### ISSUE TITLE
Sal postflight fails on 10.10.1 machine

### ISSUE THREAD

**Issue by weswhet** [salsoftware/sal#53]
Dec 01 2014 17:02:16 -0800     Performing postflight tasks...
Dec 01 2014 17:02:22 -0800     postflight stderr: Traceback (most recent call last):
  File "/usr/local/munki/postflight.d/sal-postflight", line 166, in <module>
    plist = FoundationPlist.writePlistToString(report)
  File "/usr/local/munki/munkilib/FoundationPlist.py", line 113, in writePlistToString
    raise NSPropertyListSerializationException(error)
munkilib.FoundationPlist.NSPropertyListSerializationException: Property list invalid for format (property lists cannot contain objects of type 'CFNull')
Dec 01 2014 17:02:22 -0800 ### Ending managedsoftwareupdate run ### 

Similar to https://github.com/salsoftware/sal/issues/30 but I figured I would make a new one.. 

You asked for https://gist.github.com/weswhet/0d2da58b4560cc4b0fcc on the other thread. The only other difference between this machine and other 10.10.1 machines is that he has puppet 3.4.0 installed. Before walking out he briefly mentioned that he may have change his user python.

Let me know if you need anything else.

**Comment by juosukai** [comment]
I got this error on a brand new 10.10.1 installation. I had only run the official Apple updates before installing munki (and puppet and sal). I'll try to get you some logs once I get back to the client machine (might be next week).

**Comment by grahamgilbert** [comment]
This was fixed in https://github.com/salsoftware/sal/commit/c05fdf038e154bd39bdc68d7d4d179a848d7cf1f
