### ISSUE TITLE
Sal on Docker: timezone incorrect

### ISSUE THREAD

**Issue by yagmot** [salsoftware/sal#68]
When running via Docker, the host's timezone is not respected, even when creating the container using `-e TZ=Region/City` in the `docker run` command.

More specifically, the reporting times displayed within the web interface are incorrect. The containers themselves report the correct time, as evidenced here:

`ladmin@vmus001:~$ sudo docker run --rm grahamgilbert/postgres date`
`Thu Apr  9 02:49:54 UTC 2015`

`ladmin@vmus001:~$ sudo docker run --rm -e TZ=Asia/Tokyo grahamgilbert/postgres date`
`Thu Apr  9 11:49:57 JST 2015`

**Comment by yagmot** [comment]
Found that using `-e DOCKER_SAL_TZ=Region/City` seems to fix it.

**Comment by grahamgilbert** [comment]
Yes, this is documented here: https://registry.hub.docker.com/u/macadmins/sal/
