### ISSUE TITLE
Docker Installation on Ubuntu?

### ISSUE THREAD

**Issue by adwiegel** [salsoftware/sal#69]
Hello I am still new to Docker and Linux setups so I apologize in advance if this is the wrong place or a bad question .
I followed the directions to set up Sal using Docker on my Ubuntu 14.04 server.  The setup seemed to go well and I am able to access the sal site and create business units.  It also successfully get data from the machines I set up with the sal scripts.  However I am having trouble finding the settings.py file and location of the actual sal resources.  I was hoping to add the optional plugins and the directory does not exist where it says it should even though I followed the directions exactly.  Did I miss something during my install or am I not looking in the wrong place?

I do not have a sal_env folder.  Only a sal_data folder.  This is supposedly where the files should be located.  I feel like I am missing something very obvious.  Looked all over the place and cannot find any answers so I thought I would ask here.  Thanks and sorry if this is a stupid question.

**Comment by grahamgilbert** [comment]
Hi,

Please see the section on [plugins on the Docker hub](https://registry.hub.docker.com/u/macadmins/sal/).
