### ISSUE TITLE
Pending updates showing older version number when multiple versions are pending.

### ISSUE THREAD

**Issue by duel007** [salsoftware/sal#72]
As discussed on the mailing list, updates are showing in the pending section as an older version (14.5.7) when a newer version is available and approved, and there are clients pending installs of both versions. See attached screenshots. All clients are on version 0.6.1 of the Sal scripts.
![sal1](https://cloud.githubusercontent.com/assets/5648179/11123078/b5cee3d6-8923-11e5-8199-b22c58c9ec74.PNG)
![sal2](https://cloud.githubusercontent.com/assets/5648179/11123080/b5d758cc-8923-11e5-855c-972f78715863.PNG)
![sal3](https://cloud.githubusercontent.com/assets/5648179/11123079/b5d7eada-8923-11e5-841e-68049f2e44eb.PNG)

**Comment by arubdesu** [comment]
There is no mailing list for __sal__...

**Comment by duel007** [comment]
@arubdesu sal-discuss@googlegroups.com?

**Comment by arubdesu** [comment]
right, this issue tracker is for pebbleit's product

**Comment by duel007** [comment]
Whoops, you're right. My mistake.
